In [5]:
import numpy as np
import cv2
def integral_image(inputi):
  ing_i = np.copy(inputi)
  for i in range (1, inputi.shape[0]):
    for j in range (1,inputi.shape[1]):
      ing_i[i,j] = ing_i[i-1,j] + ing_i[i,j-1] + inputi[i,j]
    return ing_i
inputi= cv2.imread("inputi.jpeg")
print('Input image = \n', inputi) 
output= integral_image(inputi)
print('Integral image = \n',output)
print(inputi.size)
print(output.size)

Input image = 
 [[[190 189 193]
  [188 187 191]
  [185 184 188]
  ...
  [210 142  99]
  [209 142  97]
  [209 142  97]]

 [[189 188 192]
  [189 188 192]
  [188 187 191]
  ...
  [213 145 102]
  [213 146 101]
  [213 146 101]]

 [[189 188 192]
  [189 188 192]
  [188 187 191]
  ...
  [216 148 105]
  [216 148 105]
  [216 148 105]]

 ...

 [[ 71  67  66]
  [ 74  70  69]
  [ 76  72  71]
  ...
  [ 45 108 142]
  [ 45 109 143]
  [ 43 110 143]]

 [[ 70  66  65]
  [ 72  68  67]
  [ 74  70  69]
  ...
  [ 45 110 141]
  [ 44 111 144]
  [ 41 110 143]]

 [[ 69  65  64]
  [ 69  65  64]
  [ 72  68  67]
  ...
  [ 45 110 141]
  [ 45 112 145]
  [ 41 110 143]]]
Integral image = 
 [[[190 189 193]
  [188 187 191]
  [185 184 188]
  ...
  [210 142  99]
  [209 142  97]
  [209 142  97]]

 [[189 188 192]
  [ 54  51  63]
  [171 166 186]
  ...
  [ 84 206 110]
  [250 238  52]
  [160  14 250]]

 [[189 188 192]
  [189 188 192]
  [188 187 191]
  ...
  [216 148 105]
  [216 148 105]
  [216 148 105]]

 ...

 [[ 71  67  66]
 